#!/bin/bash

for prefix in $@
do
  ip -6 rule add to $prefix lookup 10
  ip -6 rule add from $prefix lookup 10
done

#root@gw02:/etc/wireguard# ip -6 ru s
#0:	from all lookup local 
#10:	from all to 2a06:8187:fbab:1:: /64 lookup netz 
#10:	from all to 2a06:8187:fbab:2:: /64 lookup netz 
#10:	from 2a06:8187:fbab:1::/64 lookup netz 
#10:	from 2a06:8187:fbab:2::/64 lookup netz 
#12:	from all to 2a06:8187:fbab:1:: /64 lookup babeld 
#12:	from all to 2a06:8187:fbab:2:: /64 lookup babeld 
#12:	from 2a06:8187:fbab:1::/64 lookup babeld 
#12:	from 2a06:8187:fbab:2::/64 lookup babeld 
#32766:	from all lookup main
