#!/bin/bash
set -x
NODEPREFIX=$1
CLIENTPREFIX=$2
ip -6 rule add to $NODEPREFIX lookup 10
ip -6 rule add to $CLIENTPREFIX lookup 10
ip -6 rule add from $NODEPREFIX lookup 10
ip -6 rule add from $CLIENTPREFIX lookup 10

#root@gw02:/etc/wireguard# ip -6 ru s
#0:	from all lookup local 
#10:	from all to 2a06:8187:fbab:1:: /64 lookup netz 
#10:	from all to 2a06:8187:fbab:2:: /64 lookup netz 
#10:	from 2a06:8187:fbab:1::/64 lookup netz 
#10:	from 2a06:8187:fbab:2::/64 lookup netz 
#12:	from all to 2a06:8187:fbab:1:: /64 lookup babeld 
#12:	from all to 2a06:8187:fbab:2:: /64 lookup babeld 
#12:	from 2a06:8187:fbab:1::/64 lookup babeld 
#12:	from 2a06:8187:fbab:2::/64 lookup babeld 
#32766:	from all lookup main
